### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by cosmopol**

### CODE REVIEW

**Comment by itkach** [comment]
@MHBraun What do you think of these proposed changes?

**Comment by MHBraun** [comment]
Well, part of it is to dispute, as always with languages. Eg, I start with a capital letter at the beginning of the message, similar as in a sentence, the new proposal is to start with a small letter.

If we really want to go for pure German, where still all the English words are common knowledge, I think a better translation is
Line 17
Line 35
Line 38
Line 50
Line 79
Line 83

If we have sufficient space in the line for the messages we may switch to
Line 81
Line 84
Line 98

So far I appreciate the approach. Thanks to cosmopol.

**Comment by cosmopol** [comment]
Just drop me a line if you need German translations. I am a German native speaker.

**Comment by MHBraun** [comment]
So am I.

**Comment by francwalter** [comment]
Mee Too ;)
The most user beside Igor are German here I think.

**Comment by cosmopol** [comment]
...and Mr Tkach is from the Ukraine, right?

**Comment by ildar** [comment]
Mee Too ;)
The most user beside Igor are German here I think.


Hm, not me

**Comment by cosmopol** [comment]
OK, go for it.

**Pull request merged**
