### PR TITLE
disregard all states but merge state 'patch-3' please

### PR DESCRIPTION
**Pull request by cosmopol**
Violá, j'espère c'est ça. Si vous trouvez des erreurs, corriger les s'il vous plaît. :-)

### CODE REVIEW

**Comment by itkach** [comment]
While I'm handy with Google Translate our communication will be more efficient if you stick to English.

**Comment by cosmopol** [comment]
With French it is similar as with English. Just the capitalization at the beginning of a sentence is debatable. I do not see all those texts in Aard as whole sentences rather than tags or short notes. How about a capitalization function so you could rectify it whenever you want it however you want it.

**Comment by itkach** [comment]
> How about a capitalization function so you could rectify it whenever you want it however you want it.

How about you make it so that it does not need to be rectified.

> however you want it.

I want it to be correct, and it's translator's task to make it so.

> capitalization function

Don't get into habit of coming up with make-work for other people.

**Comment by cosmopol** [comment]
btw: I cannot follow your cyrillic writings either :-)

**Comment by cosmopol** [comment]
I did not mean to come up with make-work by proposing a capitalization function. If you have special formatting guidelines in mind, process the text on compile time. I assume in the long run it would be easier than manually checking every translation file. The content itself has to be trusted anyhow.

**Comment by itkach** [comment]
> btw: I cannot follow your cyrillic writings either :-)

yeah, but the difference is I don't want anything from you - you want something from me

**Comment by itkach** [comment]
> I did not mean to come up with make-work by proposing a capitalization function. If you have special formatting guidelines in mind, process the text on compile time. I assume in the long run it would be easier than manually checking every translation file. 

I'm not sure why do you make these assumptions. There's no magical automation, there's no processing of text at compile time. What you type in strings.xml is what application displays. It needs to be correct. Complete lack of capitalization doesn't seem to be correct and you don't seem to claim that it is correct. If you take it upon yourself to translate - do it properly, don't assume someone will clean it up.

**Comment by cosmopol** [comment]
OK, it seems you want to to start with a capital letter, but remember that that is neither correct nor wrong. I do not mean to cause additional work, rather to participate in an orderly manner.

**Comment by francwalter** [comment]
I can look into it as well next week, French is familiar to me too. Two eye pairs see more than one :)
But only next week, at the moment I am out of house.

**Comment by cosmopol** [comment]
OK, go for it.

**Comment by francwalter** [comment]
Le french looks bien :)
Moi y en a pas trouver de fautes ;)

**Comment by cosmopol** [comment]
Bien, on y va.

**Comment by cosmopol** [comment]
OK, Mr Tkach would have to merge it.

**Pull request merged**
